[tool.black]
line-length = 120
target_version = ['py27', 'py34', 'py35', 'py36', 'py37', 'py38']
exclude = '''
(
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | _build/
  | buck-out/
  | build/
  | dist/
  | ddtrace/(
    [^/]+\.py
    | bootstrap/
    | commands/
    | contrib/(
      [^/]+\.py
      | aiobotocore/
      | aiohttp/
      | aiopg/
      | algoliasearch/
      | asyncio/
      | boto/
      | botocore/
      | bottle/
      | cassandra/
      | celery/
      | consul/
      | dbapi/
      | django/
      | dogpile_cache/
      | elasticsearch/
      | falcon/
      | flask/
      | flask_cache/
      | futures/
      | gevent/
      | grpc/
      | httplib/
      | jinja2/
      | kombu/
      | logging/
      | mako/
      | molten/
      | mongoengine/
      | mysql/
      | mysqldb/
      | psycopg/
      | pylibmc/
      | pylons/
      | pymemcache/
      | pymongo/
      | pymysql/
      | pyramid/
      | redis/
      | rediscluster/
      | requests/
      | sqlalchemy/
      | sqlite3/
      | tornado/
      | urllib3/
      | vertica/
    )
    | ext/
    | http/
    | internal/
    | opentracer/
    | propagation/
    | settings/
    | utils/
    | vendor/
  )
  | tests/(
    [^/]+\.py
    | base
    | commands
    | contrib/(
      [^/]+\.py
      | aiobotocore/
      | aiohttp/
      | aiopg/
      | algoliasearch/
      | asyncio/
      | boto/
      | botocore/
      | bottle/
      | cassandra/
      | celery/
      | consul/
      | dbapi/
      | django/
      | djangorestframework/
      | dogpile_cache/
      | elasticsearch/
      | falcon/
      | flask/
      | flask_autopatch/
      | flask_cache/
      | futures/
      | gevent/
      | grpc/
      | httplib/
      | jinja2/
      | kombu/
      | logging/
      | mako/
      | molten/
      | mongoengine/
      | mysql/
      | mysqldb/
      | psycopg/
      | pylibmc/
      | pylons/
      | pymemcache/
      | pymongo/
      | pymysql/
      | pyramid/
      | redis/
      | rediscluster/
      | requests/
      | requests_gevent/
      | sqlalchemy/
      | sqlite3/
      | tornado/
      | vertica/
    )
  | internal
  | opentracer
  | propagation
  | unit
  | utils
  | vendor
  )
)
'''
